### ISSUE TITLE
Selenium IDE-SetBlocks Global: How to call function, defined in TC1 from another test case TC2

### ISSUE THREAD

**Issue by spasova** [SeLite/SeLite#11] opened 2016-05-04 19:32 UTC
Hello,

I tried to define function with function/endFunction (it contains only selenium IDE commands, actually commands to login in my app) in TC1 and to call it from TC2, but when I run the script there is infinite loop.
Actually, I want to define login steps in TC1 and to call this TC in the beginning of the other scripts.
How to do this with function/endFunction and command call?

Thank you!
Regards,
Olya Spasova

**Comment by peter-kehl** [comment] 2016-05-29 05:41
Duplicate of https://github.com/SeLite/SelBlocksGlobal/issues/1

**Closed by peter-kehl** 2016-05-29 05:41 UTC
